# Generated by Django 2.0.6 on 2019-05-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
    ]
