# Generated by Django 2.0.6 on 2019-05-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAcore', '0003_auto_20190526_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='uid',
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
