# Generated by Django 2.0.6 on 2019-05-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAcore', '0004_auto_20190526_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='uid',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
