# Generated by Django 2.0.6 on 2019-05-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAcore', '0005_auto_20190526_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avator',
            old_name='files',
            new_name='avator',
        ),
        migrations.RenameField(
            model_name='avator',
            old_name='name',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
