# Generated by Django 2.0.6 on 2019-05-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAcore', '0006_auto_20190529_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avator',
        ),
    ]
