# Generated by Django 2.0.6 on 2019-05-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAcore', '0007_remove_user_avator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator',
            field=models.ImageField(default='author_avator/default.jpg', upload_to='SAcore/static/author_avator'),
        ),
    ]
