# Generated by Django 2.0.6 on 2019-05-30 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAcore', '0009_auto_20190529_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='interested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_id', models.CharField(max_length=256)),
                ('message', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=False)),
                ('receive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_user', to=settings.AUTH_USER_MODEL)),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='publish_apply',
            name='au',
        ),
        migrations.RemoveField(
            model_name='publish_apply',
            name='authors',
        ),
        migrations.DeleteModel(
            name='publish_apply',
        ),
    ]
