# Generated by Django 2.0.6 on 2019-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAcore', '0010_auto_20190530_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='interested',
            name='patent_title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
